# Generated by Django 3.1.4 on 2020-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_AdharId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=1)),
                ('Age', models.IntegerField()),
                ('Mobile_no', models.CharField(max_length=12)),
                ('Address', models.TextField()),
                ('Pincode', models.CharField(max_length=6)),
                ('State', models.CharField(max_length=20)),
            ],
        ),

    ]
