# Generated by Django 3.0.5 on 2020-12-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
