# Generated by Django 3.0.5 on 2020-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_AdharId', models.CharField(max_length=12)),
                ('Doctor_Id', models.CharField(max_length=6)),
                ('Date_of_appointment', models.DateField()),
            ],
        ),
    ]
