# Generated by Django 3.0.5 on 2020-12-08 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Date_of_appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
