# Generated by Django 3.1.2 on 2020-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Name_hs', models.TextField()),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
                ('Address_hs', models.TextField()),
                ('Late_fine', models.CharField(max_length=20)),
            ],
        ),
    ]
