# Generated by Django 3.1.2 on 2020-11-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=12)),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=1)),
                ('Age', models.IntegerField()),
                ('Aadhar_id', models.CharField(max_length=12)),
                ('Mobile_no', models.CharField(max_length=12)),
                ('Email', models.TextField()),
                ('Qualification', models.TextField()),
                ('Area_of_specialisation', models.CharField(max_length=30)),
                ('Year_of_experience', models.IntegerField()),
                ('Type_of_practice', models.CharField(max_length=20)),
                ('Hospital_id', models.CharField(max_length=6)),
            ],
        ),
    ]
