# Generated by Django 3.0.5 on 2020-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
